services:
  - type: web
    name: eaglercraft-18-server
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    envVars:
      - key: JAVA_OPTS
        value: -Xms64M -Xmx256M -XX:+UseSerialGC
      - key: BIND_HOST
        value: 0.0.0.0
      - key: SERVER_NAME
        value: EaglerCraft Render
      - key: EAGLER_WS_PATH
        value: /
      - key: EAGLER_ALLOWED_ORIGIN
        value: '*'
      - key: ACCEPT_EULA
        value: 'true'
      - key: USE_PORT_PROXY
        value: 'true'
      - key: INTERNAL_SERVER_PORT
        value: '25565'
      - key: MINIMAL_TEMPLATE
        value: 'true'
      - key: EAGLER_JAR_URL
        sync: false
      - key: EAGLER_TEMPLATE_ZIP_URL
        value: https://github.com/Eaglercraft-Templates/Eaglercraft-Server-Paper/archive/refs/heads/main.zip
